### ISSUE TITLE
Unable to read file from GOPRO from Jellyfin (web or app)

### ISSUE THREAD

**Issue by Hazpartame** [jellyfin/jellyfin-media-player#873]
**Describe the bug**
Playback of certain GoPro HEVC video files, transcoded using VAAPI, fails immediately in Jellyfin Web. The transcoding process completes without errors (exit code 0), but the playback stops after a few seconds without displaying any video.

**To Reproduce**
1. Obtain the GoPro HEVC video file [Video](https://drive.google.com/file/d/16JPFeJqTkTKqRARKDtq0Sp2tS-10vztX/view?usp=sharing)
2. Add it to Jellyfin media library.
3. Attempt playback using Jellyfin Web.
4. Playback immediately fails and stops.

**Expected behavior**
The video should start playing normally without interruptions.

**Screenshots / Logs**
Relevant logs:
```log
[17:21:28] [INF] [25] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f mov,mp4,m4a,3gp,3g2,mj2 -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/gopro/SKI/HONECK REGIS/convertis/GX010067.MP4" [...] -y "/config/cache/transcodes/6782cff84f43bfbaccf950cc3ccb5b2a.m3u8"
[17:21:42] [INF] [21] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[17:21:49] [INF] [21] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/cache/transcodes/6782cff84f43bfbaccf950cc3ccb5b2a.m3u8
[17:21:51] [INF] [22] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.10.6 playing GX010067. Stopped at 5805 ms
```

**Desktop (please complete the following information):**
- OS: Debian 12
- Docker image: `lscr.io/linuxserver/jellyfin:latest` with VAAPI enabled via `linuxserver/mods:jellyfin-opencl-intel`
- Jellyfin Web Client Version: 10.10.6
- Installation Method: Docker Compose

**Docker Compose Configuration**
```yaml
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=107
      - PGID=113
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - database_jellyfin:/config
      - radarr_films:/movies
      - sonarr_series:/tv
      - pge:/pge
      - gopro:/gopro
      - autre:/autre
    devices:
      - /dev/dri:/dev/dri
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    ports:
      - 8096:8096
    restart: unless-stopped

volumes:
  database_jellyfin:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.44,nfsvers=4,rw"
      device: ":/mnt/database/jellyfin"
  radarr_films:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/storage/Radarr/Films"
  sonarr_series:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/storage/Sonarr/Series"
  pge:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/storage/PGE"
  gopro:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/storage/GOPRO"
  autre:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/storage/AUTRE"
```

**Additional context / File info**
File info:
- Codec: HEVC (Main 10)
- Resolution: 3840x2160
- Framerate: 59.94 fps
- Profile: Main 10

**Notes**
- File plays normally in VLC on the same PC. 
- Issue does not occur with other HEVC files transcoded similarly.
